In [2]:
import numpy as np

In [3]:
A=np.array([[1,2],[7,8]])
B=np.array([[3,5],[1,6]])

### Hitung 2*A

In [4]:
jawab1=2*A

jawab1

array([[ 2,  4],
       [14, 16]])

### Hitung 2+A

In [5]:
jawab2=2+A
jawab2

array([[ 3,  4],
       [ 9, 10]])

### Hitung A+B

In [6]:
jawab3=A+B
jawab3

array([[ 4,  7],
       [ 8, 14]])

### Hitung A-B

In [7]:
jawab4=A-B 
jawab4

array([[-2, -3],
       [ 6,  2]])

### Determinan A

In [8]:
jawab5=np.linalg.det(A)
jawab5

-6.0

### Invers dari B, simpan jadi matriks D

In [10]:
D=np.linalg.inv(B)
D

array([[ 0.46153846, -0.38461538],
       [-0.07692308,  0.23076923]])

In [12]:
jawab6=np.transpose(D)
jawab6

array([[ 0.46153846, -0.07692308],
       [-0.38461538,  0.23076923]])

### Eigen dan Vektor dari A dan B

In [13]:
print("Nilai Eigen dan Vektor dari matrix A : ",np.linalg.eig(A))
print("Nilai Eigen dan Vektor dari matrix B : ",np.linalg.eig(B))

Nilai Eigen dan Vektor dari matrix A :  (array([-0.62347538,  9.62347538]), array([[-0.77640358, -0.22592838],
       [ 0.63023605, -0.97414391]]))
Nilai Eigen dan Vektor dari matrix B :  (array([1.8074176, 7.1925824]), array([[-0.97271381, -0.76626443],
       [ 0.23200828, -0.64252535]]))
